/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AppNavbar: typeof import('./src/components/app/AppNavbar')['AppNavbar']
  const CompetitionForm: typeof import('./src/components/competition/CompetitionForm')['CompetitionForm']
  const CompetitionList: typeof import('./src/components/competition/CompetitionList')['CompetitionList']
  const ContractForm: typeof import('./src/components/player/ContractForm')['ContractForm']
  const DataTabl: typeof import('./src/components/base/DataTable')['DataTabl']
  const DataTable: typeof import('./src/components/base/DataTable')['DataTable']
  const DatePickerInput: typeof import('./src/components/base/DatePickerInput')['DatePickerInput']
  const FormationGrid: typeof import('./src/components/formation/FormationGrid')['FormationGrid']
  const InjuryForm: typeof import('./src/components/player/InjuryForm')['InjuryForm']
  const Link: typeof import('@tanstack/react-router')['Link']
  const LoanForm: typeof import('./src/components/player/InjuryForm')['LoanForm']
  const MText: typeof import('@mantine/core')['Text']
  const MatchForm: typeof import('./src/components/match/MatchForm')['MatchForm']
  const MatchTimeline: typeof import('./src/components/match/MatchTimeline')['MatchTimeline']
  const PlayerEventKey: typeof import('./src/constants/index')['PlayerEventKey']
  const PlayerEventType: typeof import('./src/constants/index')['PlayerEventType']
  const PlayerFlag: typeof import('./src/components/player/PlayerFlag')['PlayerFlag']
  const PlayerForm: typeof import('./src/components/player/PlayerForm')['PlayerForm']
  const PlayerStatus: typeof import('./src/components/player/PlayerStatus')['PlayerStatus']
  const PlayerTimeline: typeof import('./src/components/player/PlayerTimeline')['PlayerTimeline']
  const TeamAutocomplete: typeof import('./src/components/team/TeamAutocomplete')['TeamAutocomplete']
  const TeamDatePicker: typeof import('./src/components/team/TeamDatePicker')['TeamDatePicker']
  const TeamForm: typeof import('./src/components/team/TeamForm')['TeamForm']
  const appLoadingAtom: typeof import('./src/atoms/index')['appLoadingAtom']
  const assertType: typeof import('./src/utils/assert')['assertType']
  const atom: typeof import('jotai')['atom']
  const countryCodes: typeof import('./src/constants/countryCodes')['countryCodes']
  const createColumnHelper: typeof import('@tanstack/react-table')['createColumnHelper']
  const createLazyFileRoute: typeof import('@tanstack/react-router')['createLazyFileRoute']
  const createRef: typeof import('react')['createRef']
  const createRootRoute: typeof import('@tanstack/react-router')['createRootRoute']
  const dayjs: typeof import('dayjs')['default']
  const formatDate: typeof import('./src/utils/format')['formatDate']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const loadingAtom: typeof import('./src/atoms/index')['loadingAtom']
  const matchScore: typeof import('./src/utils/match')['matchScore']
  const memo: typeof import('react')['memo']
  const positions: typeof import('./src/constants/index')['positions']
  const sessionAtom: typeof import('./src/atoms/index')['sessionAtom']
  const startTransition: typeof import('react')['startTransition']
  const supabaseAtom: typeof import('./src/atoms/index')['supabaseAtom']
  const teamAtom: typeof import('./src/atoms/index')['teamAtom']
  const useAtom: typeof import('jotai')['useAtom']
  const useAtomValue: typeof import('jotai')['useAtomValue']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDbCallbacks: typeof import('./src/hooks/useDbCallbacks')['useDbCallbacks']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useNavigate: typeof import('@tanstack/react-router')['useNavigate']
  const useParams: typeof import('@tanstack/react-router')['useParams']
  const usePlayerEvents: typeof import('./src/hooks/usePlayerEvents')['usePlayerEvents']
  const useProgress: typeof import('./src/hooks/useProgress')['useProgress']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useSetAtom: typeof import('jotai')['useSetAtom']
  const useState: typeof import('react')['useState']
  const useStateRef: typeof import('react-usestateref')['default']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTeam: typeof import('./src/hooks/useTeam')['useTeam']
  const useTeamHelpers: typeof import('./src/hooks/useTeamHelpers')['useTeamHelpers']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { StateSetter } from 'src/hooks'
  import('src/hooks')
  // @ts-ignore
  export type { PlayerEventKey, PlayerEventType } from './src/constants/index'
  import('./src/constants/index')
}
