/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const TeamsIndexLazyRouteImport = createFileRoute('/teams/')()
const TeamsNewLazyRouteImport = createFileRoute('/teams/new')()
const TeamsImportLazyRouteImport = createFileRoute('/teams/import')()
const TeamsTeamIdIndexLazyRouteImport = createFileRoute('/teams/$teamId/')()
const TeamsTeamIdEditLazyRouteImport = createFileRoute('/teams/$teamId/edit')()
const TeamsTeamIdSquadsIndexLazyRouteImport = createFileRoute(
  '/teams/$teamId/squads/',
)()
const TeamsTeamIdPlayersIndexLazyRouteImport = createFileRoute(
  '/teams/$teamId/players/',
)()
const TeamsTeamIdMatchesIndexLazyRouteImport = createFileRoute(
  '/teams/$teamId/matches/',
)()
const TeamsTeamIdCompetitionsIndexLazyRouteImport = createFileRoute(
  '/teams/$teamId/competitions/',
)()
const TeamsTeamIdSeasonsIdLazyRouteImport = createFileRoute(
  '/teams/$teamId/seasons/$id',
)()
const TeamsTeamIdPlayersStatisticsLazyRouteImport = createFileRoute(
  '/teams/$teamId/players/statistics',
)()
const TeamsTeamIdPlayersNewLazyRouteImport = createFileRoute(
  '/teams/$teamId/players/new',
)()
const TeamsTeamIdPlayersDevelopmentLazyRouteImport = createFileRoute(
  '/teams/$teamId/players/development',
)()
const TeamsTeamIdPlayersAnalyticsLazyRouteImport = createFileRoute(
  '/teams/$teamId/players/analytics',
)()
const TeamsTeamIdMatchesNewLazyRouteImport = createFileRoute(
  '/teams/$teamId/matches/new',
)()
const TeamsTeamIdCompetitionsNewLazyRouteImport = createFileRoute(
  '/teams/$teamId/competitions/new',
)()
const TeamsTeamIdPlayersIdIndexLazyRouteImport = createFileRoute(
  '/teams/$teamId/players/$id/',
)()
const TeamsTeamIdMatchesIdIndexLazyRouteImport = createFileRoute(
  '/teams/$teamId/matches/$id/',
)()
const TeamsTeamIdCompetitionsIdIndexLazyRouteImport = createFileRoute(
  '/teams/$teamId/competitions/$id/',
)()
const TeamsTeamIdPlayersIdEditLazyRouteImport = createFileRoute(
  '/teams/$teamId/players/$id/edit',
)()
const TeamsTeamIdMatchesIdEditLazyRouteImport = createFileRoute(
  '/teams/$teamId/matches/$id/edit',
)()
const TeamsTeamIdCompetitionsIdEditLazyRouteImport = createFileRoute(
  '/teams/$teamId/competitions/$id/edit',
)()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TeamsIndexLazyRoute = TeamsIndexLazyRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/teams.index.lazy').then((d) => d.Route))
const TeamsNewLazyRoute = TeamsNewLazyRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/teams.new.lazy').then((d) => d.Route))
const TeamsImportLazyRoute = TeamsImportLazyRouteImport.update({
  id: '/teams/import',
  path: '/teams/import',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/teams.import.lazy').then((d) => d.Route))
const TeamsTeamIdIndexLazyRoute = TeamsTeamIdIndexLazyRouteImport.update({
  id: '/teams/$teamId/',
  path: '/teams/$teamId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/teams.$teamId.index.lazy').then((d) => d.Route),
)
const TeamsTeamIdEditLazyRoute = TeamsTeamIdEditLazyRouteImport.update({
  id: '/teams/$teamId/edit',
  path: '/teams/$teamId/edit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/teams.$teamId.edit.lazy').then((d) => d.Route),
)
const TeamsTeamIdSquadsIndexLazyRoute =
  TeamsTeamIdSquadsIndexLazyRouteImport.update({
    id: '/teams/$teamId/squads/',
    path: '/teams/$teamId/squads/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.squads.index.lazy').then((d) => d.Route),
  )
const TeamsTeamIdPlayersIndexLazyRoute =
  TeamsTeamIdPlayersIndexLazyRouteImport.update({
    id: '/teams/$teamId/players/',
    path: '/teams/$teamId/players/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.players.index.lazy').then((d) => d.Route),
  )
const TeamsTeamIdMatchesIndexLazyRoute =
  TeamsTeamIdMatchesIndexLazyRouteImport.update({
    id: '/teams/$teamId/matches/',
    path: '/teams/$teamId/matches/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.matches.index.lazy').then((d) => d.Route),
  )
const TeamsTeamIdCompetitionsIndexLazyRoute =
  TeamsTeamIdCompetitionsIndexLazyRouteImport.update({
    id: '/teams/$teamId/competitions/',
    path: '/teams/$teamId/competitions/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.competitions.index.lazy').then(
      (d) => d.Route,
    ),
  )
const TeamsTeamIdSeasonsIdLazyRoute =
  TeamsTeamIdSeasonsIdLazyRouteImport.update({
    id: '/teams/$teamId/seasons/$id',
    path: '/teams/$teamId/seasons/$id',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.seasons.$id.lazy').then((d) => d.Route),
  )
const TeamsTeamIdPlayersStatisticsLazyRoute =
  TeamsTeamIdPlayersStatisticsLazyRouteImport.update({
    id: '/teams/$teamId/players/statistics',
    path: '/teams/$teamId/players/statistics',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.players.statistics.lazy').then(
      (d) => d.Route,
    ),
  )
const TeamsTeamIdPlayersNewLazyRoute =
  TeamsTeamIdPlayersNewLazyRouteImport.update({
    id: '/teams/$teamId/players/new',
    path: '/teams/$teamId/players/new',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.players.new.lazy').then((d) => d.Route),
  )
const TeamsTeamIdPlayersDevelopmentLazyRoute =
  TeamsTeamIdPlayersDevelopmentLazyRouteImport.update({
    id: '/teams/$teamId/players/development',
    path: '/teams/$teamId/players/development',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.players.development.lazy').then(
      (d) => d.Route,
    ),
  )
const TeamsTeamIdPlayersAnalyticsLazyRoute =
  TeamsTeamIdPlayersAnalyticsLazyRouteImport.update({
    id: '/teams/$teamId/players/analytics',
    path: '/teams/$teamId/players/analytics',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.players.analytics.lazy').then(
      (d) => d.Route,
    ),
  )
const TeamsTeamIdMatchesNewLazyRoute =
  TeamsTeamIdMatchesNewLazyRouteImport.update({
    id: '/teams/$teamId/matches/new',
    path: '/teams/$teamId/matches/new',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.matches.new.lazy').then((d) => d.Route),
  )
const TeamsTeamIdCompetitionsNewLazyRoute =
  TeamsTeamIdCompetitionsNewLazyRouteImport.update({
    id: '/teams/$teamId/competitions/new',
    path: '/teams/$teamId/competitions/new',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.competitions.new.lazy').then((d) => d.Route),
  )
const TeamsTeamIdPlayersIdIndexLazyRoute =
  TeamsTeamIdPlayersIdIndexLazyRouteImport.update({
    id: '/teams/$teamId/players/$id/',
    path: '/teams/$teamId/players/$id/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.players.$id.index.lazy').then(
      (d) => d.Route,
    ),
  )
const TeamsTeamIdMatchesIdIndexLazyRoute =
  TeamsTeamIdMatchesIdIndexLazyRouteImport.update({
    id: '/teams/$teamId/matches/$id/',
    path: '/teams/$teamId/matches/$id/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.matches.$id.index.lazy').then(
      (d) => d.Route,
    ),
  )
const TeamsTeamIdCompetitionsIdIndexLazyRoute =
  TeamsTeamIdCompetitionsIdIndexLazyRouteImport.update({
    id: '/teams/$teamId/competitions/$id/',
    path: '/teams/$teamId/competitions/$id/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.competitions.$id.index.lazy').then(
      (d) => d.Route,
    ),
  )
const TeamsTeamIdPlayersIdEditLazyRoute =
  TeamsTeamIdPlayersIdEditLazyRouteImport.update({
    id: '/teams/$teamId/players/$id/edit',
    path: '/teams/$teamId/players/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.players.$id.edit.lazy').then((d) => d.Route),
  )
const TeamsTeamIdMatchesIdEditLazyRoute =
  TeamsTeamIdMatchesIdEditLazyRouteImport.update({
    id: '/teams/$teamId/matches/$id/edit',
    path: '/teams/$teamId/matches/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.matches.$id.edit.lazy').then((d) => d.Route),
  )
const TeamsTeamIdCompetitionsIdEditLazyRoute =
  TeamsTeamIdCompetitionsIdEditLazyRouteImport.update({
    id: '/teams/$teamId/competitions/$id/edit',
    path: '/teams/$teamId/competitions/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/teams.$teamId.competitions.$id.edit.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/teams/import': typeof TeamsImportLazyRoute
  '/teams/new': typeof TeamsNewLazyRoute
  '/teams': typeof TeamsIndexLazyRoute
  '/teams/$teamId/edit': typeof TeamsTeamIdEditLazyRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexLazyRoute
  '/teams/$teamId/competitions/new': typeof TeamsTeamIdCompetitionsNewLazyRoute
  '/teams/$teamId/matches/new': typeof TeamsTeamIdMatchesNewLazyRoute
  '/teams/$teamId/players/analytics': typeof TeamsTeamIdPlayersAnalyticsLazyRoute
  '/teams/$teamId/players/development': typeof TeamsTeamIdPlayersDevelopmentLazyRoute
  '/teams/$teamId/players/new': typeof TeamsTeamIdPlayersNewLazyRoute
  '/teams/$teamId/players/statistics': typeof TeamsTeamIdPlayersStatisticsLazyRoute
  '/teams/$teamId/seasons/$id': typeof TeamsTeamIdSeasonsIdLazyRoute
  '/teams/$teamId/competitions': typeof TeamsTeamIdCompetitionsIndexLazyRoute
  '/teams/$teamId/matches': typeof TeamsTeamIdMatchesIndexLazyRoute
  '/teams/$teamId/players': typeof TeamsTeamIdPlayersIndexLazyRoute
  '/teams/$teamId/squads': typeof TeamsTeamIdSquadsIndexLazyRoute
  '/teams/$teamId/competitions/$id/edit': typeof TeamsTeamIdCompetitionsIdEditLazyRoute
  '/teams/$teamId/matches/$id/edit': typeof TeamsTeamIdMatchesIdEditLazyRoute
  '/teams/$teamId/players/$id/edit': typeof TeamsTeamIdPlayersIdEditLazyRoute
  '/teams/$teamId/competitions/$id': typeof TeamsTeamIdCompetitionsIdIndexLazyRoute
  '/teams/$teamId/matches/$id': typeof TeamsTeamIdMatchesIdIndexLazyRoute
  '/teams/$teamId/players/$id': typeof TeamsTeamIdPlayersIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/teams/import': typeof TeamsImportLazyRoute
  '/teams/new': typeof TeamsNewLazyRoute
  '/teams': typeof TeamsIndexLazyRoute
  '/teams/$teamId/edit': typeof TeamsTeamIdEditLazyRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexLazyRoute
  '/teams/$teamId/competitions/new': typeof TeamsTeamIdCompetitionsNewLazyRoute
  '/teams/$teamId/matches/new': typeof TeamsTeamIdMatchesNewLazyRoute
  '/teams/$teamId/players/analytics': typeof TeamsTeamIdPlayersAnalyticsLazyRoute
  '/teams/$teamId/players/development': typeof TeamsTeamIdPlayersDevelopmentLazyRoute
  '/teams/$teamId/players/new': typeof TeamsTeamIdPlayersNewLazyRoute
  '/teams/$teamId/players/statistics': typeof TeamsTeamIdPlayersStatisticsLazyRoute
  '/teams/$teamId/seasons/$id': typeof TeamsTeamIdSeasonsIdLazyRoute
  '/teams/$teamId/competitions': typeof TeamsTeamIdCompetitionsIndexLazyRoute
  '/teams/$teamId/matches': typeof TeamsTeamIdMatchesIndexLazyRoute
  '/teams/$teamId/players': typeof TeamsTeamIdPlayersIndexLazyRoute
  '/teams/$teamId/squads': typeof TeamsTeamIdSquadsIndexLazyRoute
  '/teams/$teamId/competitions/$id/edit': typeof TeamsTeamIdCompetitionsIdEditLazyRoute
  '/teams/$teamId/matches/$id/edit': typeof TeamsTeamIdMatchesIdEditLazyRoute
  '/teams/$teamId/players/$id/edit': typeof TeamsTeamIdPlayersIdEditLazyRoute
  '/teams/$teamId/competitions/$id': typeof TeamsTeamIdCompetitionsIdIndexLazyRoute
  '/teams/$teamId/matches/$id': typeof TeamsTeamIdMatchesIdIndexLazyRoute
  '/teams/$teamId/players/$id': typeof TeamsTeamIdPlayersIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/teams/import': typeof TeamsImportLazyRoute
  '/teams/new': typeof TeamsNewLazyRoute
  '/teams/': typeof TeamsIndexLazyRoute
  '/teams/$teamId/edit': typeof TeamsTeamIdEditLazyRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexLazyRoute
  '/teams/$teamId/competitions/new': typeof TeamsTeamIdCompetitionsNewLazyRoute
  '/teams/$teamId/matches/new': typeof TeamsTeamIdMatchesNewLazyRoute
  '/teams/$teamId/players/analytics': typeof TeamsTeamIdPlayersAnalyticsLazyRoute
  '/teams/$teamId/players/development': typeof TeamsTeamIdPlayersDevelopmentLazyRoute
  '/teams/$teamId/players/new': typeof TeamsTeamIdPlayersNewLazyRoute
  '/teams/$teamId/players/statistics': typeof TeamsTeamIdPlayersStatisticsLazyRoute
  '/teams/$teamId/seasons/$id': typeof TeamsTeamIdSeasonsIdLazyRoute
  '/teams/$teamId/competitions/': typeof TeamsTeamIdCompetitionsIndexLazyRoute
  '/teams/$teamId/matches/': typeof TeamsTeamIdMatchesIndexLazyRoute
  '/teams/$teamId/players/': typeof TeamsTeamIdPlayersIndexLazyRoute
  '/teams/$teamId/squads/': typeof TeamsTeamIdSquadsIndexLazyRoute
  '/teams/$teamId/competitions/$id/edit': typeof TeamsTeamIdCompetitionsIdEditLazyRoute
  '/teams/$teamId/matches/$id/edit': typeof TeamsTeamIdMatchesIdEditLazyRoute
  '/teams/$teamId/players/$id/edit': typeof TeamsTeamIdPlayersIdEditLazyRoute
  '/teams/$teamId/competitions/$id/': typeof TeamsTeamIdCompetitionsIdIndexLazyRoute
  '/teams/$teamId/matches/$id/': typeof TeamsTeamIdMatchesIdIndexLazyRoute
  '/teams/$teamId/players/$id/': typeof TeamsTeamIdPlayersIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/teams/import'
    | '/teams/new'
    | '/teams'
    | '/teams/$teamId/edit'
    | '/teams/$teamId'
    | '/teams/$teamId/competitions/new'
    | '/teams/$teamId/matches/new'
    | '/teams/$teamId/players/analytics'
    | '/teams/$teamId/players/development'
    | '/teams/$teamId/players/new'
    | '/teams/$teamId/players/statistics'
    | '/teams/$teamId/seasons/$id'
    | '/teams/$teamId/competitions'
    | '/teams/$teamId/matches'
    | '/teams/$teamId/players'
    | '/teams/$teamId/squads'
    | '/teams/$teamId/competitions/$id/edit'
    | '/teams/$teamId/matches/$id/edit'
    | '/teams/$teamId/players/$id/edit'
    | '/teams/$teamId/competitions/$id'
    | '/teams/$teamId/matches/$id'
    | '/teams/$teamId/players/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/teams/import'
    | '/teams/new'
    | '/teams'
    | '/teams/$teamId/edit'
    | '/teams/$teamId'
    | '/teams/$teamId/competitions/new'
    | '/teams/$teamId/matches/new'
    | '/teams/$teamId/players/analytics'
    | '/teams/$teamId/players/development'
    | '/teams/$teamId/players/new'
    | '/teams/$teamId/players/statistics'
    | '/teams/$teamId/seasons/$id'
    | '/teams/$teamId/competitions'
    | '/teams/$teamId/matches'
    | '/teams/$teamId/players'
    | '/teams/$teamId/squads'
    | '/teams/$teamId/competitions/$id/edit'
    | '/teams/$teamId/matches/$id/edit'
    | '/teams/$teamId/players/$id/edit'
    | '/teams/$teamId/competitions/$id'
    | '/teams/$teamId/matches/$id'
    | '/teams/$teamId/players/$id'
  id:
    | '__root__'
    | '/'
    | '/teams/import'
    | '/teams/new'
    | '/teams/'
    | '/teams/$teamId/edit'
    | '/teams/$teamId/'
    | '/teams/$teamId/competitions/new'
    | '/teams/$teamId/matches/new'
    | '/teams/$teamId/players/analytics'
    | '/teams/$teamId/players/development'
    | '/teams/$teamId/players/new'
    | '/teams/$teamId/players/statistics'
    | '/teams/$teamId/seasons/$id'
    | '/teams/$teamId/competitions/'
    | '/teams/$teamId/matches/'
    | '/teams/$teamId/players/'
    | '/teams/$teamId/squads/'
    | '/teams/$teamId/competitions/$id/edit'
    | '/teams/$teamId/matches/$id/edit'
    | '/teams/$teamId/players/$id/edit'
    | '/teams/$teamId/competitions/$id/'
    | '/teams/$teamId/matches/$id/'
    | '/teams/$teamId/players/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  TeamsImportLazyRoute: typeof TeamsImportLazyRoute
  TeamsNewLazyRoute: typeof TeamsNewLazyRoute
  TeamsIndexLazyRoute: typeof TeamsIndexLazyRoute
  TeamsTeamIdEditLazyRoute: typeof TeamsTeamIdEditLazyRoute
  TeamsTeamIdIndexLazyRoute: typeof TeamsTeamIdIndexLazyRoute
  TeamsTeamIdCompetitionsNewLazyRoute: typeof TeamsTeamIdCompetitionsNewLazyRoute
  TeamsTeamIdMatchesNewLazyRoute: typeof TeamsTeamIdMatchesNewLazyRoute
  TeamsTeamIdPlayersAnalyticsLazyRoute: typeof TeamsTeamIdPlayersAnalyticsLazyRoute
  TeamsTeamIdPlayersDevelopmentLazyRoute: typeof TeamsTeamIdPlayersDevelopmentLazyRoute
  TeamsTeamIdPlayersNewLazyRoute: typeof TeamsTeamIdPlayersNewLazyRoute
  TeamsTeamIdPlayersStatisticsLazyRoute: typeof TeamsTeamIdPlayersStatisticsLazyRoute
  TeamsTeamIdSeasonsIdLazyRoute: typeof TeamsTeamIdSeasonsIdLazyRoute
  TeamsTeamIdCompetitionsIndexLazyRoute: typeof TeamsTeamIdCompetitionsIndexLazyRoute
  TeamsTeamIdMatchesIndexLazyRoute: typeof TeamsTeamIdMatchesIndexLazyRoute
  TeamsTeamIdPlayersIndexLazyRoute: typeof TeamsTeamIdPlayersIndexLazyRoute
  TeamsTeamIdSquadsIndexLazyRoute: typeof TeamsTeamIdSquadsIndexLazyRoute
  TeamsTeamIdCompetitionsIdEditLazyRoute: typeof TeamsTeamIdCompetitionsIdEditLazyRoute
  TeamsTeamIdMatchesIdEditLazyRoute: typeof TeamsTeamIdMatchesIdEditLazyRoute
  TeamsTeamIdPlayersIdEditLazyRoute: typeof TeamsTeamIdPlayersIdEditLazyRoute
  TeamsTeamIdCompetitionsIdIndexLazyRoute: typeof TeamsTeamIdCompetitionsIdIndexLazyRoute
  TeamsTeamIdMatchesIdIndexLazyRoute: typeof TeamsTeamIdMatchesIdIndexLazyRoute
  TeamsTeamIdPlayersIdIndexLazyRoute: typeof TeamsTeamIdPlayersIdIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/new': {
      id: '/teams/new'
      path: '/teams/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof TeamsNewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/import': {
      id: '/teams/import'
      path: '/teams/import'
      fullPath: '/teams/import'
      preLoaderRoute: typeof TeamsImportLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/edit': {
      id: '/teams/$teamId/edit'
      path: '/teams/$teamId/edit'
      fullPath: '/teams/$teamId/edit'
      preLoaderRoute: typeof TeamsTeamIdEditLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/squads/': {
      id: '/teams/$teamId/squads/'
      path: '/teams/$teamId/squads'
      fullPath: '/teams/$teamId/squads'
      preLoaderRoute: typeof TeamsTeamIdSquadsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/players/': {
      id: '/teams/$teamId/players/'
      path: '/teams/$teamId/players'
      fullPath: '/teams/$teamId/players'
      preLoaderRoute: typeof TeamsTeamIdPlayersIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/matches/': {
      id: '/teams/$teamId/matches/'
      path: '/teams/$teamId/matches'
      fullPath: '/teams/$teamId/matches'
      preLoaderRoute: typeof TeamsTeamIdMatchesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/competitions/': {
      id: '/teams/$teamId/competitions/'
      path: '/teams/$teamId/competitions'
      fullPath: '/teams/$teamId/competitions'
      preLoaderRoute: typeof TeamsTeamIdCompetitionsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/seasons/$id': {
      id: '/teams/$teamId/seasons/$id'
      path: '/teams/$teamId/seasons/$id'
      fullPath: '/teams/$teamId/seasons/$id'
      preLoaderRoute: typeof TeamsTeamIdSeasonsIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/players/statistics': {
      id: '/teams/$teamId/players/statistics'
      path: '/teams/$teamId/players/statistics'
      fullPath: '/teams/$teamId/players/statistics'
      preLoaderRoute: typeof TeamsTeamIdPlayersStatisticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/players/new': {
      id: '/teams/$teamId/players/new'
      path: '/teams/$teamId/players/new'
      fullPath: '/teams/$teamId/players/new'
      preLoaderRoute: typeof TeamsTeamIdPlayersNewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/players/development': {
      id: '/teams/$teamId/players/development'
      path: '/teams/$teamId/players/development'
      fullPath: '/teams/$teamId/players/development'
      preLoaderRoute: typeof TeamsTeamIdPlayersDevelopmentLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/players/analytics': {
      id: '/teams/$teamId/players/analytics'
      path: '/teams/$teamId/players/analytics'
      fullPath: '/teams/$teamId/players/analytics'
      preLoaderRoute: typeof TeamsTeamIdPlayersAnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/matches/new': {
      id: '/teams/$teamId/matches/new'
      path: '/teams/$teamId/matches/new'
      fullPath: '/teams/$teamId/matches/new'
      preLoaderRoute: typeof TeamsTeamIdMatchesNewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/competitions/new': {
      id: '/teams/$teamId/competitions/new'
      path: '/teams/$teamId/competitions/new'
      fullPath: '/teams/$teamId/competitions/new'
      preLoaderRoute: typeof TeamsTeamIdCompetitionsNewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/players/$id/': {
      id: '/teams/$teamId/players/$id/'
      path: '/teams/$teamId/players/$id'
      fullPath: '/teams/$teamId/players/$id'
      preLoaderRoute: typeof TeamsTeamIdPlayersIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/matches/$id/': {
      id: '/teams/$teamId/matches/$id/'
      path: '/teams/$teamId/matches/$id'
      fullPath: '/teams/$teamId/matches/$id'
      preLoaderRoute: typeof TeamsTeamIdMatchesIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/competitions/$id/': {
      id: '/teams/$teamId/competitions/$id/'
      path: '/teams/$teamId/competitions/$id'
      fullPath: '/teams/$teamId/competitions/$id'
      preLoaderRoute: typeof TeamsTeamIdCompetitionsIdIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/players/$id/edit': {
      id: '/teams/$teamId/players/$id/edit'
      path: '/teams/$teamId/players/$id/edit'
      fullPath: '/teams/$teamId/players/$id/edit'
      preLoaderRoute: typeof TeamsTeamIdPlayersIdEditLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/matches/$id/edit': {
      id: '/teams/$teamId/matches/$id/edit'
      path: '/teams/$teamId/matches/$id/edit'
      fullPath: '/teams/$teamId/matches/$id/edit'
      preLoaderRoute: typeof TeamsTeamIdMatchesIdEditLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/competitions/$id/edit': {
      id: '/teams/$teamId/competitions/$id/edit'
      path: '/teams/$teamId/competitions/$id/edit'
      fullPath: '/teams/$teamId/competitions/$id/edit'
      preLoaderRoute: typeof TeamsTeamIdCompetitionsIdEditLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  TeamsImportLazyRoute: TeamsImportLazyRoute,
  TeamsNewLazyRoute: TeamsNewLazyRoute,
  TeamsIndexLazyRoute: TeamsIndexLazyRoute,
  TeamsTeamIdEditLazyRoute: TeamsTeamIdEditLazyRoute,
  TeamsTeamIdIndexLazyRoute: TeamsTeamIdIndexLazyRoute,
  TeamsTeamIdCompetitionsNewLazyRoute: TeamsTeamIdCompetitionsNewLazyRoute,
  TeamsTeamIdMatchesNewLazyRoute: TeamsTeamIdMatchesNewLazyRoute,
  TeamsTeamIdPlayersAnalyticsLazyRoute: TeamsTeamIdPlayersAnalyticsLazyRoute,
  TeamsTeamIdPlayersDevelopmentLazyRoute:
    TeamsTeamIdPlayersDevelopmentLazyRoute,
  TeamsTeamIdPlayersNewLazyRoute: TeamsTeamIdPlayersNewLazyRoute,
  TeamsTeamIdPlayersStatisticsLazyRoute: TeamsTeamIdPlayersStatisticsLazyRoute,
  TeamsTeamIdSeasonsIdLazyRoute: TeamsTeamIdSeasonsIdLazyRoute,
  TeamsTeamIdCompetitionsIndexLazyRoute: TeamsTeamIdCompetitionsIndexLazyRoute,
  TeamsTeamIdMatchesIndexLazyRoute: TeamsTeamIdMatchesIndexLazyRoute,
  TeamsTeamIdPlayersIndexLazyRoute: TeamsTeamIdPlayersIndexLazyRoute,
  TeamsTeamIdSquadsIndexLazyRoute: TeamsTeamIdSquadsIndexLazyRoute,
  TeamsTeamIdCompetitionsIdEditLazyRoute:
    TeamsTeamIdCompetitionsIdEditLazyRoute,
  TeamsTeamIdMatchesIdEditLazyRoute: TeamsTeamIdMatchesIdEditLazyRoute,
  TeamsTeamIdPlayersIdEditLazyRoute: TeamsTeamIdPlayersIdEditLazyRoute,
  TeamsTeamIdCompetitionsIdIndexLazyRoute:
    TeamsTeamIdCompetitionsIdIndexLazyRoute,
  TeamsTeamIdMatchesIdIndexLazyRoute: TeamsTeamIdMatchesIdIndexLazyRoute,
  TeamsTeamIdPlayersIdIndexLazyRoute: TeamsTeamIdPlayersIdIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
