-- Baseline schema for the public tables in the linked Supabase project.
-- Captured from the remote database; baseline this migration on existing projects
-- with: bun run db:migrate:baseline

CREATE TABLE IF NOT EXISTS public.teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  started_on date NOT NULL,
  currently_on date NOT NULL,
  currency text NOT NULL DEFAULT '$'::text,
  game text,
  manager_name text,
  previous_id bigint,
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  badge_path text,
  CONSTRAINT teams_previousId_fkey
    FOREIGN KEY (previous_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT teams_userId_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.players (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  nationality text,
  pos text NOT NULL,
  sec_pos text[],
  ovr smallint NOT NULL,
  value bigint NOT NULL,
  birth_year smallint,
  status text,
  youth boolean NOT NULL DEFAULT false,
  kit_no smallint,
  team_id bigint NOT NULL,
  history jsonb NOT NULL DEFAULT '{}'::jsonb,
  contracts jsonb NOT NULL DEFAULT '[]'::jsonb,
  injuries jsonb NOT NULL DEFAULT '[]'::jsonb,
  loans jsonb NOT NULL DEFAULT '[]'::jsonb,
  transfers jsonb NOT NULL DEFAULT '[]'::jsonb,
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  wage integer,
  contract_ends_on date,
  import_id bigint,
  pos_order integer GENERATED ALWAYS AS (
    CASE
      WHEN (pos = 'GK'::text) THEN 0
      WHEN (pos = 'LB'::text) THEN 1
      WHEN (pos = 'LWB'::text) THEN 2
      WHEN (pos = 'CB'::text) THEN 3
      WHEN (pos = 'RB'::text) THEN 4
      WHEN (pos = 'RWB'::text) THEN 5
      WHEN (pos = 'LM'::text) THEN 6
      WHEN (pos = 'CDM'::text) THEN 7
      WHEN (pos = 'CM'::text) THEN 8
      WHEN (pos = 'CAM'::text) THEN 9
      WHEN (pos = 'RM'::text) THEN 10
      WHEN (pos = 'LW'::text) THEN 11
      WHEN (pos = 'CF'::text) THEN 12
      WHEN (pos = 'ST'::text) THEN 13
      WHEN (pos = 'RW'::text) THEN 14
      ELSE NULL::integer
    END
  ) STORED,
  CONSTRAINT players_teamId_fkey
    FOREIGN KEY (team_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT players_userId_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS index_players_on_team_id ON public.players USING btree (team_id);

CREATE TABLE IF NOT EXISTS public.matches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  team_id bigint NOT NULL,
  home_team text NOT NULL,
  away_team text NOT NULL,
  season smallint,
  competition text,
  stage text,
  played_on date NOT NULL,
  home_score smallint NOT NULL DEFAULT '0'::smallint,
  away_score smallint NOT NULL DEFAULT '0'::smallint,
  home_xg real,
  away_xg real,
  home_possession smallint DEFAULT '50'::smallint,
  away_possession smallint DEFAULT '50'::smallint,
  home_penalty_score smallint,
  away_penalty_score smallint,
  extra_time boolean NOT NULL DEFAULT false,
  friendly boolean NOT NULL DEFAULT false,
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  goals jsonb NOT NULL DEFAULT '[]'::jsonb,
  bookings jsonb NOT NULL DEFAULT '[]'::jsonb,
  import_id bigint,
  changes jsonb NOT NULL DEFAULT '[]'::jsonb,
  home_result text GENERATED ALWAYS AS (
    CASE
      WHEN (home_score > away_score) THEN 'W'::text
      WHEN (home_score < away_score) THEN 'L'::text
      ELSE 'D'::text
    END
  ) STORED,
  CONSTRAINT matches_teamId_fkey
    FOREIGN KEY (team_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT matches_userId_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS index_matches_on_team_id ON public.matches USING btree (team_id);

CREATE TABLE IF NOT EXISTS public.caps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  player_id bigint NOT NULL,
  match_id bigint NOT NULL,
  pos text NOT NULL,
  start_minute smallint NOT NULL DEFAULT '0'::smallint,
  stop_minute smallint NOT NULL DEFAULT '90'::smallint,
  num_goals smallint NOT NULL DEFAULT '0'::smallint,
  rating smallint,
  clean_sheet boolean NOT NULL DEFAULT false,
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  num_yellow_cards smallint NOT NULL DEFAULT '0'::smallint,
  num_red_cards smallint NOT NULL DEFAULT '0'::smallint,
  num_assists smallint NOT NULL DEFAULT '0'::smallint,
  ovr smallint NOT NULL,
  import_id bigint,
  pos_order smallint GENERATED ALWAYS AS (
    CASE
      WHEN (pos = 'LW'::text) THEN 0
      WHEN (pos = 'LS'::text) THEN 1
      WHEN (pos = 'ST'::text) THEN 2
      WHEN (pos = 'RS'::text) THEN 3
      WHEN (pos = 'LF'::text) THEN 4
      WHEN (pos = 'CF'::text) THEN 5
      WHEN (pos = 'RF'::text) THEN 6
      WHEN (pos = 'RW'::text) THEN 7
      WHEN (pos = 'LAM'::text) THEN 8
      WHEN (pos = 'CAM'::text) THEN 9
      WHEN (pos = 'RAM'::text) THEN 10
      WHEN (pos = 'LM'::text) THEN 11
      WHEN (pos = 'LDM'::text) THEN 12
      WHEN (pos = 'LCM'::text) THEN 13
      WHEN (pos = 'CDM'::text) THEN 14
      WHEN (pos = 'CM'::text) THEN 15
      WHEN (pos = 'RDM'::text) THEN 16
      WHEN (pos = 'RCM'::text) THEN 17
      WHEN (pos = 'RM'::text) THEN 18
      WHEN (pos = 'LB'::text) THEN 19
      WHEN (pos = 'LWB'::text) THEN 20
      WHEN (pos = 'LCB'::text) THEN 21
      WHEN (pos = 'CB'::text) THEN 22
      WHEN (pos = 'RCB'::text) THEN 23
      WHEN (pos = 'RB'::text) THEN 24
      WHEN (pos = 'RWB'::text) THEN 25
      WHEN (pos = 'GK'::text) THEN 26
      ELSE NULL::integer
    END
  ) STORED,
  num_own_goals smallint NOT NULL DEFAULT '0'::smallint,
  kit_no smallint,
  CONSTRAINT performances_matchId_fkey
    FOREIGN KEY (match_id) REFERENCES public.matches(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT performances_playerId_fkey
    FOREIGN KEY (player_id) REFERENCES public.players(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT performances_userId_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS index_appearances_on_match_id ON public.caps USING btree (match_id);
CREATE INDEX IF NOT EXISTS index_appearances_on_player_id ON public.caps USING btree (player_id);

CREATE TABLE IF NOT EXISTS public.competitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  team_id bigint NOT NULL,
  season smallint NOT NULL,
  champion text,
  stages jsonb NOT NULL DEFAULT '[]'::jsonb,
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT competitions_teamId_fkey
    FOREIGN KEY (team_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT competitions_userId_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS index_competitions_on_team_id ON public.competitions USING btree (team_id);

CREATE TABLE IF NOT EXISTS public.options (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  category text NOT NULL,
  value text NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS user_category_value
  ON public.options USING btree (user_id, category, value);

CREATE TABLE IF NOT EXISTS public.squads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  team_id bigint,
  formation jsonb NOT NULL,
  user_id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT squads_teamId_fkey
    FOREIGN KEY (team_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT squads_userId_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS index_squads_on_team_id ON public.squads USING btree (team_id);

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.caps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.squads ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'teams'
      AND policyname = 'Individuals can manage their own teams'
  ) THEN
    CREATE POLICY "Individuals can manage their own teams"
      ON public.teams FOR ALL TO public
      USING ((SELECT auth.uid()) = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'players'
      AND policyname = 'Individuals can manage their team players'
  ) THEN
    CREATE POLICY "Individuals can manage their team players"
      ON public.players FOR ALL TO public
      USING ((SELECT auth.uid()) = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'matches'
      AND policyname = 'Individuals can manage their team matches'
  ) THEN
    CREATE POLICY "Individuals can manage their team matches"
      ON public.matches FOR ALL TO public
      USING ((SELECT auth.uid()) = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'caps'
      AND policyname = 'Individuals can manage their team performances'
  ) THEN
    CREATE POLICY "Individuals can manage their team performances"
      ON public.caps FOR ALL TO public
      USING ((SELECT auth.uid()) = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'competitions'
      AND policyname = 'Individuals can manage their team competitions'
  ) THEN
    CREATE POLICY "Individuals can manage their team competitions"
      ON public.competitions FOR ALL TO public
      USING ((SELECT auth.uid()) = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'options'
      AND policyname = 'individuals can manage their options'
  ) THEN
    CREATE POLICY "individuals can manage their options"
      ON public.options FOR ALL TO public
      USING ((SELECT auth.uid()) = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'squads'
      AND policyname = 'Individuals can manage their team squads'
  ) THEN
    CREATE POLICY "Individuals can manage their team squads"
      ON public.squads FOR ALL TO public
      USING ((SELECT auth.uid()) = user_id);
  END IF;
END $$;

GRANT ALL ON TABLE public.teams TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.players TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.matches TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.caps TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.competitions TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.options TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.squads TO anon, authenticated, service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
